### PR TITLE
README: update Bootstrap homepage URL

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by cvrebert** [comment]
@digibart Ping.

**Comment by cvrebert** [comment]
@digibart Ping. This is a really tiny docs-only change.

**Comment by digibart** [comment]
sorry for the delay, could you also update the URL in readme-fr.md??

**Comment by cvrebert** [comment]
Yes, that's already part of this pull request.

**Comment by cvrebert** [comment]
Thanks

**Pull request merged**
